My:
    type: object
    config:
        fields:
            name:
                type: String
                resolve: "Hardcoded name"
            profile:
                type: UserProfile
                resolve: "@=resolver('MyProfile')"
            basket:
                type: CommerceBasket
                resolve: "@=resolver('MyBasket')"

UserAccountInput:
    type: input-object
    config:
        fields:
            username:
                type: String!
            email:
                type: String!
            password:
                type: String!

UserAccount:
    type: object
    config:
        fields:
            username:
                type: String
            email:
                type: String

# Not used for now, would require multiple user types
UserProfileInterface:
    type: interface
    config:
        fields:
            username:
                type: String
            email:
                type: String

BaseUserProfile:
    type: object
    config:
        #interfaces: [UserProfile]
        fields:
            username:
                type: String
            email:
                type: String
