My:
    type: object
    config:
        fields:
            name:
                type: String
                resolve: "Hardcoded name"
            profile:
                type: UserProfile
                resolve: "@=resolver('MyProfile')"
            basket:
                type: CommerceBasket
                resolve: "@=resolver('MyBasket')"

# @todo figure out how to make extensible
UserProfile:
    type: object
    config:
        fields:
            username:
                type: String
            email:
                type: String
            name:
                type: String
            picture:
                type: Thumbnail
