services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    EzSystems\EzPlatformGraphQL\Command\GeneratePlatformSchemaCommand:
        arguments:
            $schemaRootDir: '%ezplatform.graphql.schema.ezplatform_dir%'
        tags:
            -  { name: console.command }

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\:
        resource: '../../GraphQL/InputMapper'

    EzSystems\EzPlatformGraphQL\Security\NonAdminGraphQLRequestMatcher:
        arguments:
            $siteAccessGroups: '%ezpublish.siteaccess.groups%'

    EzSystems\EzPlatformGraphQL\GraphQL\ItemFactory: ~

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\SiteaccessGuesser\SiteaccessGuesser:
        arguments:
            $siteAccessService: '@ezpublish.siteaccess_service'
            $configResolver: '@ezpublish.config.resolver'
            $provider: '@ezpublish.siteaccess.provider'
            $siteAccessGroups: '%ezpublish.siteaccess.groups%'
