services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    EzSystems\EzPlatformGraphQL\Command\GeneratePlatformSchemaCommand:
        arguments:
            $schemaRootDir: '%ezplatform.graphql.schema.ezplatform_dir%'
        tags:
            -  { name: console.command }

    EzSystems\EzPlatformGraphQL\GraphQL\InputMapper\:
        resource: '../../GraphQL/InputMapper'

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\LocationGuesser\TreeRootLocationFilter: ~

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\LocationGuesser\MainLocationFilter: ~

    EzSystems\EzPlatformGraphQL\GraphQL\Resolver\LocationGuesser\LocationGuesser:
        class: 'EzSystems\EzPlatformGraphQL\GraphQL\Resolver\LocationGuesser\FilterLocationGuesser'
        arguments:
            $filters:
                - '@EzSystems\EzPlatformGraphQL\GraphQL\Resolver\LocationGuesser\TreeRootLocationFilter'
                - '@EzSystems\EzPlatformGraphQL\GraphQL\Resolver\LocationGuesser\MainLocationFilter'

    EzSystems\EzPlatformGraphQL\GraphQL\ItemFactory: ~
